draw_config:
  dark_mode: false
  draw_key_sides: true
  n_columns: 1
  mark_alternate_layer_activators: true
  shrink_wide_legends: 6
  glyph_tap_size: 18
  glyph_hold_size: 15
  glyph_shifted_size: 15
  svg_extra_style: |
    /* For default sytles, see https://github.com/caksoylar/keymap-drawer/blob/main/keymap_drawer/config.py#L85 */
    svg.keymap {
      font-family: Ubuntu Mono, Inconsolata, Consolas, Liberation Mono, Menlo, monospace;
      font-size: 12px;
      font-weight: bold;
      text-rendering: optimizeLegibility;
    }

    /* Technique borrowed and extended from https://github.com/englmaxi/zmk-config/blob/master/keymap-drawer/config.yaml */
    .sym_sub_text.tap {
      translate: -5px 2px;
      font-size: 20px;
    }
    .sym_sub_text.shifted {
      translate: 10px 13px;
      font-size: 10px;
      opacity: 1.0;
    }
    .combo.sym_sub_text.tap {
      translate: -1px 1px;
    }
    .combo.sym_sub_text.shifted {
      translate: 7px 5px;
      font-size: 10px;
      opacity: 1.0;
    }

    /* Variant for symbol next to symbol */
    .sym_by_sym.tap {
      translate: -6px 0px;
    }
    .sym_by_sym.shifted {
      translate: 10px 12px;
      opacity: 1.0;
    }

    :root {
      --layer-fill-lightness: 46%;
      --layer-stroke-lightness: calc(var(--layer-fill-lightness) - 8%);
      --layer-base-hue: 0;
      --layer-base-saturation: 0%;
      --layer-fill: hsl(var(--layer-base-hue), var(--layer-base-saturation), var(--layer-fill-lightness));
      --layer-stroke: hsl(var(--layer-base-hue), var(--layer-base-saturation), var(--layer-stroke-lightness));
      --layer-text: #fff;

      --fill-lightness: 82%;
      --stroke-lightness: calc(var(--fill-lightness) - 8%);

      --hrm-base-hue: 0;
      --hrm-base-saturation: 0%;
      --hrm-fill: hsl(var(--hrm-base-hue), var(--hrm-base-saturation), var(--fill-lightness));
      --hrm-stroke: hsl(var(--hrm-base-hue), var(--hrm-base-saturation), var(--stroke-lightness));
    }

    /* Key caps: Layer switch */
    .layer-default .keypos-52 rect.key,
    .layer-default .keypos-53 rect.key,
    .layer-default .keypos-54 rect.key,
    .layer-default .keypos-55 rect.key,
    .layer-default .keypos-56 rect.key,
    .layer-default .keypos-57 rect.key,
    .layer-default .keypos-64 rect.key {
      fill: var(--layer-fill);
      stroke: var(--layer-stroke);
    }
    .layer-default .keypos-52,
    .layer-default .keypos-53,
    .layer-default .keypos-54,
    .layer-default .keypos-55,
    .layer-default .keypos-56,
    .layer-default .keypos-57,
    .layer-default .keypos-64 {
      fill: var(--layer-text);
    }

    /* Key caps: Homerow mods */
    .layer-default .keypos-35 rect.key,
    .layer-default .keypos-36 rect.key,
    .layer-default .keypos-37 rect.key,
    .layer-default .keypos-38 rect.key,
    .layer-default .keypos-41 rect.key,
    .layer-default .keypos-42 rect.key,
    .layer-default .keypos-43 rect.key,
    .layer-default .keypos-44 rect.key {
      fill: var(--hrm-fill);
      stroke: var(--hrm-stroke);
    }
parse_config:
  raw_binding_map:
    "&bootloader": BOOT
    "&sys_reset": RESET
    "&caps_word": CAPS WORD
    "&ralt_gaming": Gaming
    "&rgb_ug_status_macro": RGB Status
    "&bt BT_CLR":
      tap: $$mdi:bluetooth-settings$$
      shifted: $$mdi:close-thick$$
      type: sym_sub_text
    "&bt BT_CLR_ALL":
      tap: $$mdi:bluetooth-settings$$
      shifted: $$mdi:close-thick$$
      hold: $$mdi:asterisk$$
      type: sym_sub_text
    '&bt_0':
      tap: $$mdi:bluetooth-connect$$
      shifted: '0'
      type: sym_sub_text
    '&bt_1':
      tap: $$mdi:bluetooth-connect$$
      shifted: '1'
      type: sym_sub_text
    '&bt_2':
      tap: $$mdi:bluetooth-connect$$
      shifted: '2'
      type: sym_sub_text
    '&bt_3':
      tap: $$mdi:bluetooth-connect$$
      shifted: '3'
      type: sym_sub_text
    '&out OUT_USB': $$mdi:usb$$
    '&kp KP_EQUAL': "="
    '&kp KP_DIVIDE': /
    '&kp PAUSE_BREAK': Break
    '&kp KP_MULTIPLY': "*"
    '&kp KP_MINUS': "-"
    '&kp KP_PLUS': +
    '&kp KP_DOT': .
    '&kp KP_ENTER': $$mdi:keyboard-return$$
    '&kp PSCRN': Print Screen
    '&kp SLCK': Scroll Lock
    '&kp KP_N0': "0"
    '&kp KP_N1': "1"
    '&kp KP_N2': "2"
    '&kp KP_N3': "3"
    '&kp KP_N4': "4"
    '&kp KP_N5': "5"
    '&kp KP_N6': "6"
    '&kp KP_N7': "7"
    '&kp KP_N8': "8"
    '&kp KP_N9': "9"
  zmk_keycode_map:
    # default values
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: "="
    PLUS: +
    MINUS: "-"
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH: '\'
    BSLH: '\'
    PIPE: "|"
    NON_US_BACKSLASH: '\'
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMI: ;
    COLON: ":"
    SINGLE_QUOTE: "'"
    SQT: "'"
    APOSTROPHE: "'"
    APOS: "'"
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ","
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: ">"
    GT: ">"
    LBKT: "["
    RBKT: "]"
    LBRC: "{"
    RBRC: "}"
    GRAVE: "`"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"

    # custom values
    PAGE_UP: PgUp
    PAGE_DOWN: PgDn
    HOME: Home
    INS: Ins
    END: End
    ESC: Esc
    SPACE: $$mdi:keyboard-space$$
    BSPC: $$mdi:backspace$$
    DEL: $$mdi:backspace-reverse$$
    RET: $$mdi:keyboard-return$$

    C_PP: $$mdi:play-pause$$
    C_NEXT: $$mdi:skip-forward$$
    C_PREV: $$mdi:skip-backward$$
    C_MUTE: $$mdi:volume-mute$$
    C_VOL_UP: $$mdi:volume-plus$$
    C_VOL_DN: $$mdi:volume-minus$$
    C_BRI_UP: $$tabler:brightness-up$$
    C_BRI_DN: $$tabler:brightness-down$$
    C_POWER: $$mdi:power$$
    C_SLEEP: $$mdi:power-sleep$$

    TAB: $$mdi:keyboard-tab$$
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$
    PG_UP: $$mdi:transfer-up$$
    PG_DN: $$mdi:transfer-down$$

    LCTRL: Ctrl
    RCTRL: Ctrl
    LALT: Alt
    RALT: Alt
    LSHIFT: Shift
    RSHIFT: Shift
    LGUI: Super
    RGUI: Super

    KP_NUM: Numlock
